apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- observability-operator-deployment.yaml
- observability-operator-service-account.yaml
- observability-operator-cluster-role.yaml
- observability-operator-cluster-role-binding.yaml
- observability-operator-service.yaml

images:
- name: observability-operator
  newName: observability-operator
  newTag: 0.0.20
namespace: operators

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 5m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 150Mi
  target:
    group: apps
    kind: Deployment
    version: v1
